import { DrinkType, DrinkCategory, DrinkInfo } from './types';

export const DRINKS: Record<DrinkType, DrinkInfo> = {
  [DrinkType.RED_WINE]: {
    type: DrinkType.RED_WINE,
    name: 'Punaviini',
    unit: 'pullo (75cl)',
    servingsPerUnit: 6,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.WHITE_WINE]: {
    type: DrinkType.WHITE_WINE,
    name: 'Valkoviini',
    unit: 'pullo (75cl)',
    servingsPerUnit: 6,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.ROSE]: {
    type: DrinkType.ROSE,
    name: 'Rosé',
    unit: 'pullo (75cl)',
    servingsPerUnit: 6,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.SPARKLING]: {
    type: DrinkType.SPARKLING,
    name: 'Kuohuviini',
    unit: 'pullo (75cl)',
    servingsPerUnit: 6,
    isAlcoholic: true,
    categories: [DrinkCategory.WELCOME, DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.BEER]: {
    type: DrinkType.BEER,
    name: 'Olut',
    unit: '24-pack',
    servingsPerUnit: 24,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.CIDER]: {
    type: DrinkType.CIDER,
    name: 'Siideri',
    unit: '24-pack',
    servingsPerUnit: 24,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.LONKERO]: {
    type: DrinkType.LONKERO,
    name: 'Lonkero',
    unit: '24-pack',
    servingsPerUnit: 24,
    isAlcoholic: true,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.VODKA]: {
    type: DrinkType.VODKA,
    name: 'Vodka',
    unit: 'pullo (70cl)',
    servingsPerUnit: 16,
    isAlcoholic: true,
    categories: [DrinkCategory.EVENING],
  },
  [DrinkType.GIN]: {
    type: DrinkType.GIN,
    name: 'Gin',
    unit: 'pullo (70cl)',
    servingsPerUnit: 16,
    isAlcoholic: true,
    categories: [DrinkCategory.EVENING],
  },
  [DrinkType.NON_ALC_SPARKLING]: {
    type: DrinkType.NON_ALC_SPARKLING,
    name: 'Alkoholiton kuohuviini',
    unit: 'pullo (75cl)',
    servingsPerUnit: 6,
    isAlcoholic: false,
    categories: [DrinkCategory.WELCOME, DrinkCategory.DINNER],
  },
  [DrinkType.NON_ALC_BEER]: {
    type: DrinkType.NON_ALC_BEER,
    name: 'Alkoholiton olut',
    unit: '24-pack',
    servingsPerUnit: 24,
    isAlcoholic: false,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.NON_ALC_CIDER]: {
    type: DrinkType.NON_ALC_CIDER,
    name: 'Alkoholiton siideri',
    unit: '24-pack',
    servingsPerUnit: 24,
    isAlcoholic: false,
    categories: [DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.JUICE]: {
    type: DrinkType.JUICE,
    name: 'Mehu',
    unit: 'pullo (1,5L)',
    servingsPerUnit: 6,
    isAlcoholic: false,
    categories: [DrinkCategory.WELCOME, DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.SODA]: {
    type: DrinkType.SODA,
    name: 'Limsa',
    unit: 'pullo (1,5L)',
    servingsPerUnit: 6,
    isAlcoholic: false,
    categories: [DrinkCategory.WELCOME, DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
  [DrinkType.MINERAL_WATER]: {
    type: DrinkType.MINERAL_WATER,
    name: 'Kivennäisvesi',
    unit: 'pullo (1,5L)',
    servingsPerUnit: 6,
    isAlcoholic: false,
    categories: [DrinkCategory.WELCOME, DrinkCategory.DINNER, DrinkCategory.EVENING],
  },
};
